# Generated by Django 3.1.3 on 2020-11-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
